<!DOCTYPE  html>
<html>
<meta charset="UTF-8">
<head><title>myBlog</title></head>
<body>

<h1>Login Page</h1>
<p>Please Login to Continue</p>

<form action ="?" method="POST">
<label for="username">Username:</label>
	<input type="text" name="username" id="username" maxlength="20" size="20" /> <br />
<label for="password">Password:</label>	
	<input type="password" name="password" id="password" maxlength="20" size="20" /><br />
<input type="submit" />
</form>


	
	
	
