<!doctype html>
<html>
<head>
<meta charset="UTF-8">
<title>Login</title>
</head>

<body>
<h1>Members Area</h1>
<p>Please log in with your username and password below. </p>
<form action="?" method="post">
<label for="username">Username:</label>
<input type="text" name="username" id="UserName" maxlength="20" /><br> 
<label for="password">Password:</label>
<input type="text" name="password" placeholder="Password" maxlength="20" /><br> 
<input type="submit" value="Login">
</form>
